displayName=Proximity Voice Chat
author=dezz
support=https://dezz.tv
description=The first ever proximity voice chat plugin.
tags=dezz, thisdezz, darkgoul, dmoneigh, runescape, proximity, voicechat, proxiscape 
plugins=com.jcscllc.proxiscape.ProxiScapePlugin
build=gradle