displayName=Proximity Voice Chat
author=dezz
support=https://dezz.tv
description=The only DEDICATED proximity voice chat plugin.
tags=dezz,thisdezz,darkgoul,dmoneigh,runescape,proximity,voicechat,proxiscape,proxychat
plugins=com.jcscllc.proxiscape.ProxiScapePlugin
build=gradle