displayName=dezz
author=Desmond Jackson
description=The first ever proximity voice chat plugin.
tags=dezz, thisdezz, darkgoul, dmoneigh, runescape, proximity, voicechat, proxiscape 
plugins=com.jcscllc.proxiscape.ProxiScapePlugin
build=standard